name: Deploy Minha Obra

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rlgoDzvc -i"
            SOURCE: "nginx/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ vars.PATH_TO_DEPLOY }}
            SCRIPT_BEFORE: |
              whoami
              ls -la ~/app/nginx
            SCRIPT_AFTER: |
              whoami
              ls -la ~/app/nginx
              echo $RSYNC_STDOUT
